[package]
name = "rtask"
version = "0.1.0"
authors = ["Moritz Ulrich <moritz@tarn-vedra.de>"]

[dependencies]
rustc-serialize = "0.3"
libc = "0.2"
log = "0.3"
env_logger = "0.3"
rusqlite = "*"

[dependencies.bincode]
version = "0.6"
features = ["rustc-serialize"]
default-features = false

[dependencies.time]
version = "0.1"
features = ["rustc-serialize"]

[dependencies.uuid]
version = "0.2"
features = ["rustc-serialize", "v4"]
